export const settings= {
    classHidden:'hidden',
    classActive:'active',
    classSectionPrimaryMenu:'.section-primary-menu',
    classCompetence:'.competence',
    classInfoCompetence:'.info-competence',
    classCapaciteVideo:'.capacite-video',
    classCapaciteText:'.capacite-text',
    classCapaciteLogo:'.capacite-logo',
    idNavReseaux:'nav-reseaux',
    idBoutonReseaux:'button-reseaux',
    idBurgerMenu:'burger-menu',
    idPrimaryMenu:'primary-menu',
    idNavBurgerMenu:'nav-burger-menu',
    idCloseBurgerMenu:'close-burger-menu',
    idCloseReseauxMenu:'close-reseaux-menu',
}